package:
  name:  anacor
  version:  1.0

source:
  path: .

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip

  run:
    - python
    - opencv
    - importlib-metadata
    - scikit-image
    - numba
    - imagecodecs
    - dials
